### PR TITLE
Doctor online and offline & open or close video consultation registration

### PR DESCRIPTION
**Pull request by ShiqiDing**
1. Realize the back-end function of online and offline doctors on the web side

2. Enable or close video consultation registration

### CODE REVIEW

**Comment by ShiqiDing** [comment]
Well done! We chose to adopt it after checking and testing, and hope to see more contributions from you!

**Comment by GoldWaterFall** [comment]
Well done! We chose to adopt it after checking and testing, and hope to see more contributions from you!

**Comment by ShiqiDing** [comment]
I would like to ask what you will use to test your code. I see that there is no testing part such as unit testing.

**Comment by GoldWaterFall** [comment]
We will use the restkit tool to check whether the function is normal.

**Comment by GoldWaterFall** [comment]
After confirmation, we have unified our opinions. The database fields should be written in English, and the comments should also be written in English. I hope you can make changes next time you submit.

**Comment by ShiqiDing** [comment]
This resolves #7

**Pull request merged**
